login_url : "http://fake-tsinghua-id.herokuapp.com/login/form/6a87628c7342cae7e66a2a5cc375531a/0/new_login"
appid : "eval_system"
ticket_url : "http://fake-tsinghua-id.herokuapp.com/checkticket/eval_system/"